spring:
  datasource:
    url: jdbc:mysql://10.18.32.161:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: hcp
    password: Hcp@123_2020
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 3000
      pool-name: dd
      max-lifetime: 90000
      connection-timeout: 1000
      connection-test-query: SELECT 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10100/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}