#服务名端口号
server:
  port: 10201

#Spring相关配置
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dangzhicairang/my-config.git
          username: dangzhicairang
          password: cr410124
          search-paths: my-cloud

#服务注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    #注册url
    service-url:
      defaultZone: http://localhost:10100/eureka

#开启所有监控中心接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS