zuul:
  routes:
    static:
      path: /static/**
      serviceId: http://localhost:10302/static/
    chartInfo:
      path: /chartInfo/**
      serviceId: http://localhost:10302/chartInfo/
    jobinfo:
      path: /jobinfo/**
      serviceId: http://localhost:10302/jobinfo/
    joblog:
      path: /joblog/**
      serviceId: http://localhost:10302/joblog/
    jobgroup:
      path: /jobgroup/**
      serviceId: http://localhost:10302/jobgroup/
    user:
      path: /user/**
      serviceId: http://localhost:10302/user/
    help:
      path: /help/**
      serviceId: http://localhost:10302/help/
