eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER}:10101/eureka
  server:
    enable-self-preservation: false

spring:
  cloud:
    inetutils:
      preferred-networks: 192.168.0