eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${random.int}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://my-eureka1:10101/eureka,http://my-eureka2:10101/eureka
  server:
    enable-self-preservation: false